### ISSUE TITLE
Remove built in margins in definition list

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-layout#113]
Definition list has built-in right and bottom margins which causes layout issues with surrounding content. Margin should be removed so consumers can use recommended spacing techniques for layout.

**Comment by Blackbaud-RakeshGarg** [comment]
We have migrated the SPA into Sky4 and looking for the resolution on this bug.

**Comment by Blackbaud-AlexKingman** [comment]
Consumers should be using the new description list component instead of the definition list. It will alleviate the concerns behind this issue and also introduce more effective responsive layouts and different modes.

See documentation for new component here:
https://developer.blackbaud.com/skyux-layout/docs/description-list
