### ISSUE TITLE
Action button outline extends outside of container

### ISSUE THREAD

**Issue by Blackbaud-DanielCooke** [blackbaud/skyux-layout#52]
### Actual behavior
Clicking on an action button in Chrome causes an outline that overflows the action button container.

### Steps to reproduce
Using Chrome
Go to [demo](https://developer.blackbaud.com/skyux/components/action-button#demo)
Apply focus to any of the action buttons (click and drag away or apply from developer tools)

### Severity
Low
### Impact
Low

The Chrome user agent style sheet is applying the outline to the anchor element.
The display:block style from sky-action-button-icon and sky-action-button-header are causing the overflow

**Comment by Blackbaud-AdamSc** [comment]
This occurs in Edge Chromium as well.

**Comment by Blackbaud-AdamSc** [comment]
I can fix this.  Need some input on what color we want the outline to be when in focus. Currently it is different per browser (Edge = Black, Firebox = fine dotted black, Chrome = light blue),  was going to use the light blue '$sky-background-color-info'.

**Comment by Blackbaud-AdamSc** [comment]
@blackbaud/skyux-maintainers

**Comment by Blackbaud-AdamSc** [comment]
The fix is to set the `outline` to none, then on focus add `box-shadow` to the element with it set to look like a solid thin line similar looking to what is already the behavior.  `box-shadow` will follow the slightly rounded border of the button.  Could use `outline` on focus here but it has square corners, which doesn't look bad given our button is very slightly rounded on the corners.
